### ISSUE TITLE
使用rest-client发送POST请求时，请求体中的json存在中文乱码; 同样的数据用curl发送就不会存在这种问题

### ISSUE THREAD

**Issue by palagend** [wisdomtool/rest-client#10]

**Comment by witpool** [comment]
默认编码格式是UTF-8，支持中文的，这个是测试过的用例，能否提供一下你测试时显示的乱码字符？

**Comment by palagend** [comment]
![用rest-client发送的请求是乱码](https://user-images.githubusercontent.com/12581767/33974095-8c824250-e0c1-11e7-935c-a32ef9fc0963.png)

![用curl发送的请求没有乱码](https://user-images.githubusercontent.com/12581767/33974103-92ae05c4-e0c1-11e7-9d0a-8293a6075d15.png)

![控制台的输出结果，用rest-client请求输出的是问号，用curl请求的是正常文字](https://user-images.githubusercontent.com/12581767/33974152-e4f9d4a2-e0c1-11e7-824c-3e9dbb41c431.png)

**Comment by witpool** [comment]
非常感谢您的问题反馈，已经解决中文乱码问题，请下载使用最新的rest-client工具！
