### ISSUE TITLE
非常好的一個工具

### ISSUE THREAD

**Issue by chy89310** [wisdomtool/rest-client#13]
目前見到可以改善的地方
1. Response可以考慮格式化顯示json數據。
2. Response裡面考慮使用utf8mb4編碼，我測試的時候都是unicode編碼的，不知道是不是我的問題

**Comment by witpool** [comment]
謝謝您對工具的肯定，後續版本會改進！

**Comment by witpool** [comment]
Response目前是支持对XML，HTML，JSON进行格式化
支持主流的大众的UTF-8编码格式，但是支持到细粒度的utf8mb4这个不是大众通用的，不建议使用。
