### ISSUE TITLE
测试request请求每次都生成history记录问题

### ISSUE THREAD

**Issue by lingqibaobei** [wisdomtool/rest-client#14]
生成API文档，默认根据History列表中去生成的，但是，我在测request的时候，并不一定就是成功的，所以同一个接口要测好多次，这样就都添加到history中去了，然后每次生成API文档的时候，还要手动删除无用记录，感觉有点不合理；

Generate API documents, according to the default History list to generate, but when I was in request, is not necessarily successful, so the same interface to test several times, so they are added to the history to go, then every time when generating API documents, but also manually delete the useless record, feeling is not reasonable

**Comment by witpool** [comment]
非常感谢您对WisdomTool rest-client在使用中遇到的问题进行反馈。history 的定位是记录用户的一切request，无论是成功的还是失败的。
可能有些记录并不适合用户去生成API文档或者去retest。所以在历史信息列表里增加可供选择的选项框比较合理，很好的反馈，下个版本会做优化。

**Comment by witpool** [comment]
在restclient-1.2.jar里做了优化，对返回为null的请求不记录到history里
