### ISSUE TITLE
建议出一个mac版本的wisdomtool

### ISSUE THREAD

**Issue by Andywugh** [wisdomtool/rest-client#18]
用java直接执行工具，基本测试restful是可以用的，但是导出和生成报表或api文档时，可能只支持windows的目录路径结构导致不能生成，望能做一个mac方便下苹果用户谢谢

**Comment by witpool** [comment]
的确有这个问题，之前有人也邮件反馈过，不过你可以尝试用浏览器打开如下文件，也能看到生成的报表和API文档页面。
**_work/report/report.html
work/apidoc/apidoc.html_**
后续版本的rest-client会解决这个问题，更好支持mac。
非常感谢您的问题反馈！

**Comment by witpool** [comment]
对于Mac还有linux目前restclient-1.2.jar在功能上是支持的，只是执行结束，不能默认启用浏览器打开测试报告或API文档，需要根据弹出的提示信息手动用浏览器打开如下文件:
work/report/report.html
work/apidoc/apidoc.html
