### ISSUE TITLE
能不能自动生成随机参数啊？

### ISSUE THREAD

**Issue by witslan** [wisdomtool/rest-client#26]
能不能自动生成随机参数啊？

**Comment by witpool** [comment]
随机参数具体是应用于API测试还是API文档？能否给出详细解释？

**Comment by witslan** [comment]
API测试，比如一个参数不止一个值，我怎样模拟生成这些参数？而不是手动输入。

**Comment by witpool** [comment]
这个就太随意了，自动生成何种类型的参数，在哪个位置上生成，给哪个API使用，任何工具都很难做到，不过可以为工具做一些辅助工具，比如生成随机参数，加密，解密等等，已经有类似问题报过来

https://github.com/wisdomtool/rest-client/issues/17

**Comment by witslan** [comment]
对啊，大概就是这样啊
