### ISSUE TITLE
请不要恶意使用Github

### ISSUE THREAD

**Issue by chao** [wisdomtool/rest-client#27]
@wisdomtools 你想推广你的软件，我理解，也希望你的软件能够获得你期望的用户。一直在mozilla官网上给RESTClient插件低分我也没意见。但是你直接在RESTClient项目的wiki中发你的软件的说明，这就过分了。

希望你能好好做好自己的软件开发，通过正常的渠道推广。

**Comment by chao** [comment]
![screen shot 2018-03-01 at 1 12 56 pm](https://user-images.githubusercontent.com/55872/36828094-89eb6b48-1d52-11e8-8ebc-220877b6fcda.png)
![screen shot 2018-03-01 at 1 13 07 pm](https://user-images.githubusercontent.com/55872/36828097-8b4558f0-1d52-11e8-8e3b-cc83c2311418.png)

配图

**Comment by witpool** [comment]
下来跟内部人员明确一下，非常抱歉！

**Comment by witpool** [comment]
ss

**Comment by witpool** [comment]
下来跟内部人员明确一下，非常抱歉！
